cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<int:product_id>', remove, name='product_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('photo.urls')),
    path('', include('shop.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from django.views.generic.detail import DetailView


from .views import *
from .models import Photo

app_name = 'photo'

urlpatterns = [
    path('', photo_list, name='photo_list'),
    path('detail/<int:pk>/', PhotoDetailView.as_view(model=Photo, template_name='photo/detail.html'), name='photo_detail'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('delete/<int:pk>/', PhotoDeleteView.as_view(), name='photo_delete'),
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
    path('mypage/', Mypage.as_view(), name='mypage'),
]

photo/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    address = models.CharField(max_length=10, default='')
    postal_code = models.CharField(max_length=10, default='')
    city = models.CharField(max_length=10, default='')


class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_photos')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default='photos/no_image.png')
    text = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated']

    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d%H:%M:%S")

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=[str(self.id)])

photo/views.py
from django.shortcuts import render, redirect

from .models import Photo
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView


# Create your views here.

def photo_list(request):
  photos = Photo.objects.all()
  return render(request, 'photo/list.html', {'photos': photos})


class PhotoUploadView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/upload.html'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id  # 현재 로그인 한 사용자로 설정
        if form.is_valid():  # 입력된 값 검증
            form.instance.save()  # 이상이 없다면, 데이터베이스에 저장하고,
            return redirect('photo:photo_list')  # 메인 페이지로 이동
        else:
            return self.render_to_response({'form': form})  # 이상이 있다면, 작성된 내용을 그대로 작성 페이지에 표시


class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    success_url = '/'  # site 메인 의미
    template_name = 'photo/delete.html'


class PhotoUpdateView(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/update.html'


class PhotoDetailView(LoginRequiredMixin, DetailView):
    model = Photo
    template_name = 'photo/detail.html'


class Mypage(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'photo/mypage.html'

photo/templates/photo/delete.html
{% extends 'base.html' %}
{% block title %}- Delete{% endblock %}

{% block content %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'photo/upload.css' %}">

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <div class="alert alert-info">
            Do you want to delete {{object}}?
        </div>
        <form action="" method="post">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Confirm">
            <input type="button" class="btn btn-outline-danger" onclick="history.back()" value="Cancel">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

photo/templates/photo/detail.html
{% extends 'base.html' %}
{% block title %}
    {{object.text|truncatechars:10}}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <p><img src="{{object.photo.url}}" style="width:100%;"></p>
        <button type="button" class="btn btn-outline-primary btn-sm">
            {{object.author.username}}
        </button>
        <p>{{object.text|linebreaksbr}}</p>
        <a href="{% url 'photo:photo_delete' pk=object.id %}" class="btn btn-outline-danger btn-sm float-right">Delete</a>
        <a href="{% url 'photo:photo_update' pk=object.id %}" class="btn btn-outline-success btn-sm float-right">Update</a>
    </div>
    <div class="col-md-2"></div>
</div>
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        {% load disqus_tags %}
        {% disqus_show_comments %}
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

photo/templates/photo/list.html
{% extends 'base.html' %}
{% block title %}- List{% endblock %}

{% block content %}
{% for post in photos %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <p><img src="{{post.photo.url}}"style="width:100%;"> </p>
        <button type="button" class="btn btn-xs btn-info">
            {{post.author.username}}
        </button>
        <p>{{post.text|linebreaksbr}}</p>
        <p class="text-right">
            <a href="{% url 'photo:photo_detail' pk=post.id %}" class="btn btn-xs btn-success">댓글달기</a>
        </p>
    </div>
    <div class="col-md-2"></div>
</div>

{% endfor %}
{% endblock %}

photo/templates/photo/mypage.html
{% extends 'base.html' %}
{% block title %}
    Mypage
{% endblock %}

{% block content %}

    <h1><span class="half_highlight">My Page</span></h1><br>

<b> User name: </b>  {{ user.username }}<br><br>
<b> First name: </b> {{ user.first_name }}<br><br>
<b> Last name: </b> {{ user.last_name }}<br><br>
<b> Email: </b> {{ user.email }}<br><br>
<b> Address: </b> {{ user.address }}<br><br>
<b> Postalcode: </b> {{ user.postal_code }}<br><br>
<b> City: </b> {{ user.city }}

</body>
{% endblock %}

photo/templates/photo/update.html
{% extends 'base.html' %}
{% block title %}- Update{% endblock %}

{% block content %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'photo/upload.css' %}">

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <form action="" method="post" enctype="multipart/form-data">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Update">
            <input type="button" class="btn btn-outline-danger" onclick="history.back()" value="Cancel">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

photo/templates/photo/upload.html
{% extends 'base.html' %}
{% block title %}- Upload{% endblock %}

{% block content %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'photo/upload.css' %}">

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
    <form action="" method="post" enctype="multipart/form-data">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Upload">
    </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}